# Description: Settings for the application
# 此為Compiler的設定檔案，用來設定輸出的路徑，以及類別的參數設定 (如果砍掉會在執行檔案目錄生成一個)
# 注意每層必須是兩個空格，不然會讀不到!!!!

version: 1.0.0
ue_generator_code_output_dir: ""
ue_project_name: SGF

parent_class:
  # Name : 類別名稱 #Name# 為讀取的Proto檔案中的名稱
  name: UProtobuf
  # parent_class_name : 繼承的父類別名稱
  parent_class: UObject
  class_macro: UCLASS()
  property_macro: UPROPERTY()

child_class:
  class_macro: UCLASS(BlueprintType, Blueprintable)
  property_macro: UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SGF|ProtobufMessage")
  
enum_class:
  macro: UENUM(BlueprintType)