name: protobuf_to_unreal_cpp
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  protobuf: ^3.1.0
  protoc_plugin: ^21.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
